spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: config

server:
  port: 80

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证 
  user:
    name: user                  # 配置登录的账号是user
    password: 123456            # 配置登录的密码是password123
