spring:
  profiles:
    active: test

server:
  port: 8080

notify:
  url:
    ind: http://backend:8080/api/anon/auth/account/notify
    log: http://39.108.120.120/fcl/fclAcenterController.do?notify

