spring:
  profiles:
    active: test

server:
  port: 8080

notify:
  url:
    ind: http://backend:7080/api/anon/auth/account/notify
    log: http://e-fcl.test.fengchaoli.com/fclAcenterController.do?notify

