spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: aucenter
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.76.215.203:3306/fengchao_acenter?useUnicode=true&amp;characterEncoding=UTF-8
      username: fcl_dev_sa
      password: 5vcB#RBaHCuWdTbDrKt4$pBvEHfcbhGb
      platform: mysql
  jpa:
      hibernate:
        ddl-auto: update
  data:
      rest:
        basePath: /api

server:
  port: 9999

logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG


security:
  oauth2:
    resource:
      filter-order: 3

notify:
  url:
    ind: http://localhost:9090
    log: http://localhost:8090

