spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: api-gateway
#  cloud:
#    config:
#      uri: http://${config.host:192.168.1.140}:${config.port:8888}

server:
  port: 8080

zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      #serviceId: ucenter
      url: http://localhost:9999/
    order:
      path: /order/**
      sensitiveHeaders:
      #serviceId: backend  //先屏蔽服务发现
      url: http://localhost:8083/
  add-proxy-headers: false

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false