logging:
  level:
    org.springframework.security: INFO
  path: ../logs

server:
  port: 80   #使用docker容器，默认都采用80端口

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  instance:
    prefer-ip-address: true
    #ip-address: ${spring.application.name}
    #instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://registry/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://ucenter/uaa/current
    client:
      clientId: server
      clientSecret: server
      accessTokenUri: http://ucenter/uaa/oauth/token
      grant-type: client_credentials
      scope: server
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
#  datasource:
#    url: jdbc:mysql://localhost:3306/cola-cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    db-name: cola-cloud
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 8
#    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: 1
#      max-idle: 8
#      min-idle: 0

flyway:
  baselineOnMigrate: true

management:
  security:
    enabled: false

#mybatis配置
#mybatis-plus:
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用