server:
  context-path: /common
  port: 6006

cola:
  storage:
    type: aliyun
    oss:
      access-key-id:
      access-key-secret:
      bucket-name: honvay-cola
      endpoint: oss-cn-hangzhou.aliyuncs.com
  vc:
    sms:
      template-code: SMS_115750106
      code-param-name: code
      sign-name: Cola云平台
