hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  debug:
    request: true
  routes:
    ucenter:
        path: /uaa/**
        serviceId: ucenter
        #stripPrefix: true
        sensitiveHeaders:
    fcl:
        path: /fcl/**
        sensitiveHeaders:
        #stripPrefix: true
        serviceId: sidecar
        #url: http://192.168.10.143:8080/fcl