   spring:
      sleuth:
          enabled: false
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://120.76.215.203:3306/fengchao_acenter?useUnicode=true&amp;characterEncoding=UTF-8
          username: fcl_dev_sa
          password: 5vcB#RBaHCuWdTbDrKt4$pBvEHfcbhGb
          platform: mysql
   zipkin:
      storage:
          type: mysql